### ISSUE TITLE
Como puedo generar uno propio?

### ISSUE THREAD

**Issue by johnfelipe** [TEDICpy/PAVotaciones#1]
Como puedo generar uno propio?
Gracias
Quedo atento

**Comment by lupa18** [comment]
Hola Felipe. ¿Qué es lo que quieres generar?
Este software se basa en Decada Votada, desarrollado en Argentina.
TEDIC lo adaptó para que funcione con mysql y generó un parseador para poder procesar los RTF que genera la cámara de diputados de Paraguay.

**Comment by johnfelipe** [comment]
Hola amigo, lo q deseo hacer es una version para las votaciones en algun concejo, asamblea de colombia, quedo atento

**Comment by lupa18** [comment]
Como te decía. Nuestro software es una adaptación de http://www.decadavotada.com.ar
En nuestro caso, solo tenemos corriendo la parte de diputados porque los senadores en Paraguay no registran el voto. 

Lo que hicimos fue desconectar la parte de fusion tables de google y hacer el almacenamiento de información con una Base de Datos MySQL. 

En el [README.md](https://github.com/TEDICpy/PAVotaciones/blob/master/README.md) encontrarás las instrucciones para crear tu propia instalación. Si necesitas más ayuda o quieres seguir dialogando puedes escribirme a mi correo de trabajo: lupa en tedic.org
